### ISSUE TITLE
SO! MANY! ISSUES!

### ISSUE THREAD

**Issue by VitskyDs** [udacity/exoplanet-explorer#12]
This course id dimply outdated. Every dependency is deprecated.

**Comment by forrestw92** [comment]
First off follow the installation guide in the README then run these commands.

`npm install -g npm-check-updates`
`ncu -u`
`npm install`
`bower install`
I was also having a issue with jshint so run this if necessary
` npm install --save-dev jshint gulp-jshint`

**Comment by Herbrandus** [comment]
The instructions in the README and the commands listed here above my reply do not really solve anything. Installing `npm-check-updates` works, but from there on I get lists of npm errors with every command. It doesn't seem to install or do anything.
![image](https://user-images.githubusercontent.com/8873260/42411010-404a6a00-81f4-11e8-8957-f1194a6e5ffc.png)

**Comment by adkuca** [comment]
It didn't work for me on Windows, but I tried it on Linux (ubuntu/mint) and it worked. There it gave me this option while installing:
Unable to find a suitable version for test-fixture, please choose one by typing one of the numbers below:
    1) test-fixture#^1.0.0 which resolved to 1.1.2 and is required by polymer-starter-kit
    2) test-fixture#^3.0.0 which resolved to 3.0.0 and is required by web-component-tester#6.5.0
I chose first. Anyway, copy pasted directory back to windows and viola.
I didn't check the versions of node etc that I installed

**Comment by kraftaa** [comment]
I got the same options on windows, have chosen 1st and it worked
