### ISSUE TITLE
Install without Issues

### ISSUE THREAD

**Issue by lloan** [udacity/exoplanet-explorer#13]
Here are the instructions to get this project up and running. Hope this saves someone some time!

Note: As pointed out by @breinert, you must be running your terminal with admin rights. 

Instructions: (this will also download polymer starter kit and install it) 
- git clone https://github.com/udacity/exoplanet-explorer.git (thanks @thedelk for pointing out)
- cd exoplanet-explorer
- npm install -g gulp bower
- npm install && bower install -f polymer-starter-kit
- gulp serve

Reference: https://stackoverflow.com/questions/50281186/my-local-server-cant-find-bower-files-when-i-run-my-application/50997199#50997199

**Comment by ec-miller** [comment]
Thank you @lloan !

**Comment by Danny-G-Smith** [comment]
If you use these instructions have you already dowloaded polymer and placed it in a subdirectory as  polymer-starter-kit, or is it downloaded per you install above?

**Comment by lloan** [comment]
@Danny-G-Smith Nope, you download them with these instructions. `npm install && bower install -f polymer-starter-kit` - bower is a package manager. Let me know if you get stuck.

**Comment by breinert** [comment]
Not sure if it is just me but I had to run git Bash as admin before this would work. Thanks so much for the help.

**Comment by lloan** [comment]
@breinert No, you definitely have a point. I have my Git Bash to run as Admin by default, so I oversaw that step. I'll add it to the original post.

**Comment by theclavedj** [comment]
Thank you! Everything went well after following your indications

**Comment by lloan** [comment]
@theclavedj Glad it helped!

**Comment by thedelk** [comment]
The link [https://github.com/udacity/exoplanet.explorer.git](https://github.com/udacity/exoplanet.explorer.git) is broken.

It should be [https://github.com/udacity/exoplanet-explorer](https://github.com/udacity/exoplanet-explorer).

That being said, thank you for this.  The course is missing the polymer install.

**Comment by lloan** [comment]
@thedelk Updated. Thanks! And it does include it, but there's just too much going on that its not clear enough.

**Comment by stucflo** [comment]
Thanks for the help here, I am up and running now.

**Comment by lloan** [comment]
@stucflo good to hear!

**Comment by feezo** [comment]
I had followed every instruction and the installation went well, but when I tried to make an http request by creating promise and chain it as per the quiz lesson video , I get a blank page with the following error logged in console

![console error](https://user-images.githubusercontent.com/32906922/45596496-96335b00-b9b4-11e8-9a92-3a55f53f4d5e.PNG)

**Comment by lloan** [comment]
> I had followed every instruction and the installation went well, but when I tried to make an http request by creating promise and chain it as per the quiz lesson video , I get a blank page with the following error logged in console
> 
> ![console error](https://user-images.githubusercontent.com/32906922/45596496-96335b00-b9b4-11e8-9a92-3a55f53f4d5e.PNG)

Looks like you didn't install polymer, you must have skipped `npm install && bower install -f polymer-starter-kit` - if running this command doesn't help, I suggest just starting from scratch in a new directory, following each step above.

**Comment by feezo** [comment]
@lloan 

> > I had followed every instruction and the installation went well, but when I tried to make an http request by creating promise and chain it as per the quiz lesson video , I get a blank page with the following error logged in console
> > ![console error](https://user-images.githubusercontent.com/32906922/45596496-96335b00-b9b4-11e8-9a92-3a55f53f4d5e.PNG)
> 
> Looks like you didn't install polymer, you must have skipped `npm install && bower install -f polymer-starter-kit` - if running this command doesn't help, I suggest just starting from scratch in a new directory, following each step above.

Thanks for the reply . I started a new directory and followed the steps above and all is now fine

**Comment by a-ali** [comment]
I got this output after running `gulp server`:

```console
$ gulp server
Using gulpfile /path/to/exoplanet-explorer/gulpfile.js
Task 'server' is not in your gulpfile
Please check the documentation for proper gulpfile formatting
```

I've no experience with Gulp, but I checked `gulpfile.js` and noticed that at lines `179` and `213` there are two tasks named `serve` and `serve:dist`

```javascript
gulp.task('serve', ['styles', 'elements', 'images'], function () { // 179
gulp.task('serve:dist', ['default'], function () { // 213
```

I changed them to:

```javascript
gulp.task('server', ['styles', 'elements', 'images'], function () { // 179
gulp.task('server:dist', ['default'], function () { // 213
```

and everything is working fine now.

**Comment by lloan** [comment]
> I got this output after running `gulp server`:
> 
> ```
> $ gulp server
> Using gulpfile /path/to/exoplanet-explorer/gulpfile.js
> Task 'server' is not in your gulpfile
> Please check the documentation for proper gulpfile formatting
> ```
> 
> I've no experience with Gulp, but I checked `gulpfile.js` and noticed that at lines `179` and `213` there are two tasks named `serve` and `serve:dist`
> 
> ```js
> gulp.task('serve', ['styles', 'elements', 'images'], function () { // 179
> gulp.task('serve:dist', ['default'], function () { // 213
> ```
> 
> I changed them to:
> 
> ```js
> gulp.task('server', ['styles', 'elements', 'images'], function () { // 179
> gulp.task('server:dist', ['default'], function () { // 213
> ```
> 
> and everything is working fine now.

The original error is just telling you that task doesn't exist. That's because you typed `server` instead of `serve`. But you can definitely change that task name to whatever you'd like. :)

**Comment by MicahBala** [comment]
Thanks for this guide spent hours repeating the instructions in the course and i keep getting errors. This saved me. Thanks. @lloan

**Comment by jkbiggs** [comment]
I too have spent hours repeating the instructions on how to configure gulp, bower, and polymer, but have had no luck.  I've tried deleting and reinstalling following the exact instructions above, but keep getting "gulp: command not found".  Weird, when I could locate gulpfile.js.  Then I tried deleting all of gulp and bower and just trying to use `polymer init starter-kit` but that gives me the same error.  

Any ideas?  I've got the latest node, npm and polymer packages

**Comment by lloan** [comment]
> I too have spent hours repeating the instructions on how to configure gulp, bower, and polymer, but have had no luck. I've tried deleting and reinstalling following the exact instructions above, but keep getting "gulp: command not found". Weird, when I could locate gulpfile.js. Then I tried deleting all of gulp and bower and just trying to use `polymer init starter-kit` but that gives me the same error.
> 
> Any ideas? I've got the latest node, npm and polymer packages

@jkbiggs Are you cloning and navigating to the new directory, then running your commands there? 

In your case, try installing gulp locally: `npm install gulp` and try again.

**Comment by marwanbshara** [comment]
@lloan Hey Thank you for the help of installing process.
I wanted to note out that I get many of WARN such as:
`npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer`
What does this mean and how it could be solved?
Thank you

**Comment by jkbiggs** [comment]
@lloan thanks for the help.  I am doing exactly as the instructions say.  cloning the git project, cd'ing into the new directory, and running all the npm installations inside the local directory.  Still getting `gulp: command not found`. 

However, I'm able to use the newly embedded server inside polymer-starter-kit by typing `polymer serve`.

**Comment by lloan** [comment]
@jkbiggs 

Did you try installing gulp locally instead of globally? The instructions above use the global flag, have you tried installing gulp within the project root? `npm install gulp` - very odd. 

Can you print what version of npm you have? 

Try `npm --version` and `node -v` and `gulp -v` - what does it say?

**Comment by lloan** [comment]
> @lloan Hey Thank you for the help of installing process.
> I wanted to note out that I get many of WARN such as:
> `npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js npm WARN deprecated hoek@0.9.1: The major version is no longer supported. Please update to 4.x or newer`
> What does this mean and how it could be solved?
> Thank you

@marwanbshara if I recall correctly, those are dependencies. Unless you're getting issues that are impeding you from working on the project, those should just be noise. Essentially, its recommending you upgrade to graceful-fs 4 - its a warning. We're you able to work on the exoplanet project?

**Comment by hbkwong** [comment]
Closing this for now (currently linked classroom content, however). Feel free to re-open or submit a PR if issues still come up!

**Comment by ghost** [comment]
I got problems running this repo :(

**Comment by SidoPillai** [comment]
@lloan Thank you. It worked for me. I had remove all refs and install everything from scratch.

**Comment by pawelczuczwara** [comment]
Hello. 
I did already repeated installation four times, installing all dependencies, 
but not with && because it is not working. 
I just run them separately.
I run everything as admin.

Please help. How should I proceed, to advance with the project?

With gulp serve 
i got no errors:
[PSK] Serving files from: .tmp
[PSK] Serving files from: app
[18:25:55] Starting 'jshint'...

In the browser, I can see header with blue background: Exoplanet Explorer, Learn more about planets around other stars!, as the attached image:
![captura](https://user-images.githubusercontent.com/45513983/50701659-c596d200-104e-11e9-85a3-2d67aab7fa2d.JPG)

However. 
During npm install, I got error of gyp, asking me to install VCBuild.exe:
Do I REALLY need Visual Studio 2005 to run this project?

This is complete installation log:
[exoplanet_installation.txt](https://github.com/udacity/exoplanet-explorer/files/2728074/exoplanet_installation.txt)

**Comment by ghost** [comment]
> 
> 
> Hello.
> I did already repeated installation four times, installing all dependencies,
> but not with && because it is not working.
> I just run them separately.
> I run everything as admin.
> 
> Please help. How should I proceed, to advance with the project?
> 
> With gulp serve
> i got no errors:
> [PSK] Serving files from: .tmp
> [PSK] Serving files from: app
> [18:25:55] Starting 'jshint'...
> 
> In the browser, I can see header with blue background: Exoplanet Explorer, Learn more about planets around other stars!, as the attached image:
> ![captura](https://user-images.githubusercontent.com/45513983/50701659-c596d200-104e-11e9-85a3-2d67aab7fa2d.JPG)
> 
> However.
> During npm install, I got error of gyp, asking me to install VCBuild.exe:
> Do I REALLY need Visual Studio 2005 to run this project?
> 
> This is complete installation log:
> [exoplanet_installation.txt](https://github.com/udacity/exoplanet-explorer/files/2728074/exoplanet_installation.txt)

Not necessarily, if you haven't already, try running this command at elevated permissions:
`$ npm i -g windows-build-tools`

Sometimes you just haven't installed the [build tools](https://www.npmjs.com/package/windows-build-tools), you don't require the program to run the project.

**Comment by Leny73** [comment]
Hey guys I'm trying to review the course and have a look at this project I follow the instructions but I end up with a screen like @pawelczuczwara giving me a certain error on the console : 
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
Seems like the project is not supported anymore ?

**Comment by pawelczuczwara** [comment]
It should be explained a Little better what should be initial app state.
The screen is ok, you have just start coding... try follow the course...

**Comment by Data-Sigh-tist** [comment]
Hi there!, I have completed the first  4 bullet points successfully. But when I run the last or 5th bullet point "gulp serve" I am getting the following error message. Any Idea.
=============================================
fs.js:27
const { Math, Object, Reflect } = primordials;
                                  ^

ReferenceError: primordials is not defined
    at fs.js:27:35
    at req_ (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by lloan** [comment]
> # Hi there!, I have completed the first 4 bullet points successfully. But when I run the last or 5th bullet point "gulp serve" I am getting the following error message. Any Idea.
> fs.js:27
> const { Math, Object, Reflect } = primordials;
> ^
> 
> ReferenceError: primordials is not defined
> at fs.js:27:35
> at req_ (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\natives\index.js:143:24)
> at Object.req [as require] (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\natives\index.js:55:10)
> at Object. (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
> at Module._compile (internal/modules/cjs/loader.js:759:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
> at Module.load (internal/modules/cjs/loader.js:628:32)
> at Function.Module._load (internal/modules/cjs/loader.js:555:12)
> at Module.require (internal/modules/cjs/loader.js:666:19)
> at require (internal/modules/cjs/helpers.js:16:16)

What is this file `fs.js` for? Is it part of the project or a module?

**Comment by Data-Sigh-tist** [comment]
I have no idea what file is this "fs.js". I don't have such file in my project folder.

**Comment by Data-Sigh-tist** [comment]
Oh, I see I do have this file in my project folder at this location:
\exoplanet-explorer\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js.  Not sure, it got there, all I see in that file this one following command:

"""module.exports = require('natives').require('fs', ['stream'])"""

Any idea now?

**Comment by igorzanine** [comment]
> Oh, I see I do have this file in my project folder at this location:
> \exoplanet-explorer\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js. Not sure, it got there, all I see in that file this one following command:
> 
> """module.exports = require('natives').require('fs', ['stream'])"""
> 
> Any idea now?

i'm getting the same error, has it been ever resolved by any chance? could you share it?

**Comment by shivabayar** [comment]
> > # Hi there!, I have completed the first 4 bullet points successfully. But when I run the last or 5th bullet point "gulp serve" I am getting the following error message. Any Idea.
> > fs.js:27
> > const { Math, Object, Reflect } = primordials;
> > ^
> > ReferenceError: primordials is not defined
> > at fs.js:27:35
> > at req_ (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\natives\index.js:143:24)
> > at Object.req [as require] (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\natives\index.js:55:10)
> > at Object. (C:\Users\Hafiz\documents\FrontEndWebDev\exoplanet-explorer\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
> > at Module._compile (internal/modules/cjs/loader.js:759:30)
> > at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
> > at Module.load (internal/modules/cjs/loader.js:628:32)
> > at Function.Module._load (internal/modules/cjs/loader.js:555:12)
> > at Module.require (internal/modules/cjs/loader.js:666:19)
> > at require (internal/modules/cjs/helpers.js:16:16)
> 
> What is this file `fs.js` for? Is it part of the project or a module?

I am getting the same error , i ran `npm install -g gulp bower && npm install && bower install -f polymer-starter-kit` and post that I ran `gulp serve`, which when i got this error
I have following versions of node `npm gulp and bower`
![image](https://user-images.githubusercontent.com/7943591/58373175-99b9b180-7f47-11e9-9f43-55784cc43a99.png)

**Comment by tuliren** [comment]
> const { Math, Object, Reflect } = primordials;
> ^
> ReferenceError: primordials is not defined

There is some incompatibility issue between gulp 3 and the latest version of node (version 12), which caused this error. Try an earlier version of node (e.g. I used `8.15.1` locally) and it should work.

**Comment by AndrewSultann** [comment]
I followed the instructions more than once, and it is really failing.
something is wrong, whenever I check after I install the dependencies it tells me 'gulp is not recognized as an internal or external command!!!
I need help :)

**Comment by frivas** [comment]
I have just cloned the repo and got the same error as @tuliren. I found this [Fix Error](https://timonweb.com/posts/how-to-fix-referenceerror-primordials-is-not-defined-error/) and it works.

**Comment by JVarona6** [comment]
I also recieved the same issue...

ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (/Users/johnvarona/Desktop/Workspace/Udacity-Projects/exoplanet-explorer/exoplanet-explorer/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/johnvarona/Desktop/Workspace/Udacity-Projects/exoplanet-explorer/exoplanet-explorer/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/johnvarona/Desktop/Workspace/Udacity-Projects/exoplanet-explorer/exoplanet-explorer/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)

**Comment by samadarshad** [comment]
Thank you! It worked for me.
Note I had to install specific version of gulp:

`npm install -g gulp@3.8.5`

and use node version 10.

`nvm install 10`
`nvm use 10`

Update:
I'm having issues with building and vulcanizing the project using `gulp`, therefore I'll just stick with `gulp serve` for now.

**Comment by haydard** [comment]
> Thank you! It worked for me.
> Note I had to install specific version of gulp:
> 
> `npm install -g gulp@3.8.5`
> 
> and use node version 10.
> 
> `nvm install 10`
> `nvm use 10`
> 
> Update:
> I'm having issues with building and vulcanizing the project using `gulp`, therefore I'll just stick with `gulp serve` for now.

I had the same issue as  @Data-Sigh-tist and the solution of @samadarshad worked for me.

**Comment by heldernoid** [comment]
> I have just cloned the repo and got the same error as @tuliren. I found this [Fix Error](https://timonweb.com/posts/how-to-fix-referenceerror-primordials-is-not-defined-error/) and it works.

I followed that one but then got `.tmpDir is not a function`. any clue?

**Comment by Dvloper-Ibrahim** [comment]
> Here are the instructions to get this project up and running. Hope this saves someone some time!
> 
> Note: As pointed out by @breinert, you must be running your terminal with admin rights.
> 
> Instructions: (this will also download polymer starter kit and install it)
> 
> * git clone https://github.com/udacity/exoplanet-explorer.git (thanks @thedelk for pointing out)
> * cd exoplanet-explorer
> * npm install -g gulp bower
> * npm install && bower install -f polymer-starter-kit
> * gulp serve
> 
> Reference: https://stackoverflow.com/questions/50281186/my-local-server-cant-find-bower-files-when-i-run-my-application/50997199#50997199

Please, I need help :
I created an external 'server.js' outside 'app' folder, and I attached it with this folder and set my server and ran localhost from it .
and when I opened my console I found this message :
![Capture](https://user-images.githubusercontent.com/90285256/145487654-9d4f6306-1af4-46f8-99d8-e3bf838a8cbf.PNG)

**Comment by derrynknife** [comment]
> > I have just cloned the repo and got the same error as @tuliren. I found this [Fix Error](https://timonweb.com/posts/how-to-fix-referenceerror-primordials-is-not-defined-error/) and it works.
> 
> I followed that one but then got `.tmpDir is not a function`. any clue?

I had this issue. I started from scratch and was able to get it running.

1. Delete git folder
2. uninstall node (using brew on my Mac)
3. installed nvm
4. installed nvm version 10 (`nvm install 10`)
5. download git and cd into it
5. installed gulp version 3.8.5 (`npm install -g gulp@3.8.5`)
6. installed bower (`npm install -g bower`)
7. run the final install `npm install && bower install -f polymer-starter-kit`
8. `gulp serve`
