### ISSUE TITLE
Error not catched in Fetch API exercise solution (1.12)

### ISSUE THREAD

**Issue by mcornella** [udacity/exoplanet-explorer#3]
[This `catch` is not triggered](https://github.com/udacity/exoplanet-explorer/blob/fetch-solution/app/scripts/app.js#L55) when the URL passed to `getJSON` is wrong. Instead, the execution goes into the first `then` which triggers the following error:

```
SyntaxError: Unexpected token C
```

I've found that that is a result of our `response.json()` in `getJSON` because we're [trying to parse what is already a JSON object](http://stackoverflow.com/a/23760745). So the solution is we need to `catch` this error after the `response.json()`, something like this:

``` diff
diff --git a/app/scripts/app.js b/app/scripts/app.js
index fad2918..ab505dd 100644
--- a/app/scripts/app.js
+++ b/app/scripts/app.js
@@ -39,7 +39,9 @@ Instructions:
    */
   function getJSON(url) {
     return get(url).then(function(response) {
-      return response.json();
+      return response.json().catch(function() {
+        return Error('Network Error');
+      });
     });
   }
```

I'm a super noob about Promises and the Fetch API, so I had to find the idea of `catch`ing a `response.json()` call from [this @jakearchibald post](https://jakearchibald.com/2015/thats-so-fetch/). Probably there's even a better way to catch this, so please let me know.

Thanks for the course, so far so good! :blush:

**Comment by cameronwp** [comment]
Sorry for the massive delay here. If you submit a PR, I'll be happy to take a look.
